# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day25.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)

        self.title.setGeometry(QtCore.QRect(300, 30, 800, 50))
        self.title.setFont(QtGui.QFont('DFKai-SB', 24))
        self.title.setObjectName("title")

        self.label_videoframe = QtWidgets.QLabel(self.centralwidget)
        self.label_videoframe.setGeometry(QtCore.QRect(50, 100, 640, 480))
        self.label_videoframe.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_videoframe.setObjectName("label_videoframe")
        self.label_videoframe.setAlignment(QtCore.Qt.AlignCenter)

        self.button_opencam = QtWidgets.QPushButton(self.centralwidget)
        self.button_opencam.setGeometry(QtCore.QRect(780, 150, 160, 60))
        self.button_opencam.setFont(QtGui.QFont('Times New Roman', 12))
        self.button_opencam.setEnabled(True)
        self.button_opencam.setVisible(True)
        self.button_opencam.setObjectName("button_opencam")

        self.button_pred = QtWidgets.QPushButton(self.centralwidget)
        self.button_pred.setGeometry(QtCore.QRect(780, 150, 160, 60))
        self.button_pred.setFont(QtGui.QFont('Times New Roman', 12))
        self.button_pred.setEnabled(False)
        self.button_pred.setVisible(False)
        self.button_pred.setObjectName("button_pred")

        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(780, 300, 160, 60))
        self.button_exit.setFont(QtGui.QFont('Times New Roman', 12))
        self.button_exit.setObjectName("button_exit")
        self.button_exit.setVisible(True)

        self.button_restart = QtWidgets.QPushButton(self.centralwidget)
        self.button_restart.setGeometry(QtCore.QRect(780, 300, 160, 60))
        self.button_restart.setFont(QtGui.QFont('Times New Roman', 12))
        self.button_restart.setObjectName("button_reboot")
        self.button_restart.setVisible(False)

        self.label_pred = QtWidgets.QLabel(self.centralwidget)
        self.label_pred.setGeometry(QtCore.QRect(730, 450, 180, 120))
        self.label_pred.setFont(QtGui.QFont('Times New Roman', 18))
        self.label_pred.setObjectName("label_filepath")

        self.label_level = QtWidgets.QLabel(self.centralwidget)
        self.label_level.setGeometry(QtCore.QRect(780, 450, 300, 120))
        self.label_level.setFont(QtGui.QFont('Times New Roman', 24))
        self.label_level.setObjectName("label_level")

        self.statusBar = QtWidgets.QStatusBar(self.centralwidget)
        self.statusBar.setGeometry(QtCore.QRect(780, 450, 180, 120))
        self.statusBar.setObjectName("statusBar")
        self.statusBar.setFont(QtGui.QFont('Times New Roman', 12))
        MainWindow.setStatusBar(self.statusBar)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基於臉部表情辨識與壓力測量之海關測謊系統"))
        self.title.setText(_translate("MainWindow", "謊言偵測系統"))
        self.button_opencam.setText(_translate("MainWindow", "Opencam"))
        self.button_pred.setText(_translate("MainWindow", "Predict"))
        self.button_exit.setText(_translate("MainWindow", "Exit"))
        self.button_restart.setText(_translate("MainWindow", "Restart"))
        self.label_pred.setText(_translate("MainWindow", "Level:"))
        self.label_level.setText(_translate("MainWindow","     --"))
        self.statusBar.showMessage(str('         系統啟動，請開啟鏡頭'), 50000)

        img = cv2.imread('C:/Users/Hung/Downloads/frame.jpeg', cv2.IMREAD_COLOR)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        height, width, channel = img.shape
        bytesPerline = 3 * width
        qimg = QtGui.QImage(img, width, height, bytesPerline, QtGui.QImage.Format_RGB888)
        qpixmap = QtGui.QPixmap.fromImage(qimg)
        self.label_videoframe.setScaledContents(True)
        self.label_videoframe.setPixmap(qpixmap)
        self.label_videoframe.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)  # Center




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())